spring.application.name=airdrop
server.port=8080

# PostgreSQL (Neon) Configuration
spring.datasource.url=jdbc:postgresql://ep-red-cell-azn1frvj.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_O19DIpdknmWf

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring Security Admin Credentials
spring.security.user.name=admin
spring.security.user.password=Grkannan@2678
